language: groovy
jdk:
- oraclejdk8
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
before_script:
- rm -rf build
script: "./travis-build.sh"
env:
  global:
  - secure: kgjmeeK5L/9MjbWDvgxaZ2STRIx4UtCz0Y0gkxOcewf7YEdtRbLpmQO/hRpCEBSHu2dnqilVsHa44aaDvjl+l+RWcIteHdAM8Ocg+ZpvU+ArjkkbIZDgAScrZrSUIH7WCWDC2OI5U8UfE6cS+3dseDa7zMJ7w8gpc4xY9CBv37E=
  - secure: EdnemSUp5Mxhgur75PK4q4Id9+FKHDqy+vglQW4kkCfOgWK07u8WZsV20ytHL2+WpHDesRvWDKoR1Lzu8Vh4O7evdrJI5s50TQM+772RUAZNbARDHCzuJ2FJmb2SJwooeecWrbOIj68SLGd7aYtydB27q4oh2njGAD6oneZJiBs=
  - secure: SRIwnGP/pS25TUureuWApAUVeGKKa+UpRCntExKda3F+X3CVaFGXB58GZNX5QnLwEJb4tczSW6p9+/Kwo+F/2+FYN8zbURo1IyAFWylWW8t96axu5Mh0bB0ftAu51cfaxYpWWDC5tW1xtIuTsHoj3FDD9iI2mG4vJGH+ltYoOp0=
  - secure: VbeeclxGNhp22+RF1X/UM0HKL9+SnQcTaj3qqNwRj5KmZbQCQYT8DdYepzTWBkx8t8GI2po9DdkTFxkEat2zR5tHzVqShrTSHc2HVPxZzSqf7WfuYuHKhgXm9wlea1JcLgsvP5z2zpD5mKDsJN6uvgDFlgebvCv0YLgo6p5InGI=
  - secure: evMblW9Q4O7dr1cgRoZ8SOEJ0fJ46c88ek50dsLdd53MItGmT6DGgEGBydOamNVdAnJRi7VEFOhFUz215zeNGLJQSArCXrU8TsGfYR/eYzztNBxZXKvdDP+E65N0UkJjBeQe6AJ9IZlEkwWYgT2ZxmMvEvGe+cVHmoiTTSHm+7A=
  - secure: mVjdLk0Xw74MEu996x5gBcqQeJpAIMkcADbQfGO9kc80eRimXqB2OP5etXF6dpCBauc4w5tGGbTxk7gFSQ4hvByh79ESwAVVInOrITSW8m9NCw+34AxZzQo9Vtwv7c8O/XJjEVuNjpQQ3A9ST6mfblzXZ7jSfz+tMYXBUwA9Ero=
  - secure: uDOQgOVJlOG0KTAca9BqOJL/gF12jHkrLLIGbSkNHgJ9Vr/MTQ04ix4El7IriCvOTsK3Dcj7pltxPmumVjSEmc3sUGgjH9lDVMWQZKFzZt8H/57E77nsvcHktsxydY5meISe4/NffZkQfKqxdoOvRLrcBH9/ZG862VNIkMoAV2k=
