grails:
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartContexts:
                - test
---
server:
    port: 0
---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:
    dbCreate: none
    url: jdbc:h2:mem:singleDb
